// Module Configuration Format
// ["functionPrefix", "module", "functionFile", execute <int>[0 = exec, 1 = fnc, 2 = both]]

DD_Modules = DD_Modules + [
  ["OL",    "misc", "LoadingSetText",      1],
  ["OL",    "misc", "ratioKick",           1],
  ["OL",    "misc", "10MCleanUp",          1],
  ["OL",    "misc", "CheckWater",          1],
  ["OL",    "misc", "ratioChecker",        1],
  ["OL",    "misc", "TreeFixer",           1],
  ["OL",    "misc", "PDFunctions",         1],
  ["OL",    "misc", "dialogPlayerlist",    1],
  ["OL",    "misc", "EMSFunctions",        1],
  ["OL",    "misc", "FosterFireCheck",     1],
  ["OL",    "misc", "ChatMessage",         1],
  ["OL",    "misc", "ForceFeed",           1],
  ["OL",    "misc", "isPistol",            1],
  ["OL",    "misc", "hasPistol",           1],
  ["OL",    "misc", "briefing",            1],
  ["OL",    "misc", "escapemod",           1],
  ["OL",    "misc", "Markers",             1],
  ["OL",    "misc", "isProne",             1],
  ["OL",    "misc", "SayDirectSpeach",     1],
  ["OL",    "misc", "resetJailCode",       1],
  ["OL",    "misc", "Hunger",              1],
  ["OL",    "misc", "Radar",               0],
  ["OL",    "misc", "addLicense",          1],
  ["CP",    "misc", "ArrayOffsetSelector", 1],
  ["CP",    "misc", "ArrayOffsetTrimmer",  1],
  ["CP",    "misc", "ArrayCargoCombiner",  1],
  ["CP",    "misc", "ArrayOffsetDelete",   1],
  ["CP",    "misc", "ArrayTrimStart",      1],
  ["CP",    "misc", "GetVehicleType",      1],
  ["CP",    "misc", "GetRandomCode",       1],
  ["CP",    "misc", "whereYouAtTho",       1],
  ["CP",    "misc", "ArrayObj2Str",        1],
  ["CP",    "misc", "ArrayStr2Obj",        1],
  ["CP",    "misc", "StringSearch",        1],
  ["CP",    "misc", "NearestCar",          1],
  ["CP",    "misc", "countArray",          1],
  ["CP",    "misc", "AntiDupe",            1],
  ["Item",  "misc", "Bunnyhop",            1],
  ["Item",  "misc", "CPR",                 1]
];
