#include "_shoparrays.sqf"
INV_itemmaxstocks = [-1];
INV_itemstocks 		= [-1];

INV_ItemShops = [
	[OL_Shop_Undercover,			"Undercover Police Equipment",				OL_Shop_Undercover,		ccarspawnuc,			_undercover,				_undercover,				true],
	[OL_Shop_ClothingStore,		"Civilian Clothing Shop",							dummyobj,							dummyobj,					M_rlrpgclothing,		M_rlrpgclothing,		true],
	[OL_Shop_ClothingStore_1,	"Military Surplus",										dummyobj,							dummyobj,					M_rlrpgclothing_1,	M_rlrpgclothing_1,	true],
	[OL_Shop_ClothingStore_2,	"Tactical Military Clothing",					dummyobj,							dummyobj,					M_rlrpgclothing_2,	M_rlrpgclothing_2,	true],
	[OL_Shop_ClothingStore_3,	"Civilian Clothing Shop",							dummyobj,							dummyobj,					M_rlrpgclothing,		M_rlrpgclothing,		true],
	[OL_Shop_ClothingStore_4,	"Military Surplus",										dummyobj,							dummyobj,					M_rlrpgclothing_1,	M_rlrpgclothing_1,	true],
	[OL_Shop_Pistol,					"Licensed Pistol",										pistol,								pistol,						_pistol,						_pistol,						true],
	[sub,									"Submachine Gun",											sub,						sub,							_sub,								_sub,								true],
	[rifle,								"Licensed Rifle",											rifle,					rifle,						_rifle,							_rifle,							true],
	[guss,								"Illegal Fire Arms",									gussbox,				dummyobj,					_guss,							_guss,							true],
	[txwshop,							"Tier X Weapons",											weaponx,				weaponx,					_weaponx,						_weaponx,						true],
	[txeshop,							"Tier X Equipment",										itemx,					itemx,						_itemx,							_itemx,							true],
	[carx,								"Tier X Vehicles",										carx,						carxspawn,				_carx,							_carx,							true],
	[boatx,								"Tier X Boats",												boatx,					boatxspawn,				_boatx,							_boatx,							true],
	[helix,								"Tier X Helicopters",									helix,					helixspawn,				_helix,							_helix,							true],
	[fuel2,								"Fuel-station Shop",									dummyobj,				dummyobj,					_fs,								_fs,								true],
	[fuel4,								"Fuel-station Shop",									dummyobj,				dummyobj,					_fs,								_fs,								true],
	[fuel5,								"Fuel-station Shop",									dummyobj,				dummyobj,					_fs,								_fs,								true],
	[fuel7,								"Fuel-station Shop",									dummyobj,				dummyobj,					_fs,								_fs,								true],
	[fuel8,								"Fuel-station Shop",									dummyobj,				dummyobj,					_fs,								_fs,								true],
	[shop1,								"Food Shop",													dummyobj,				dummyobj,					_is,								_is,								true],
	[shop4,								"Food Shop",													dummyobj,				dummyobj,					_is,								_is,								true],
	[bailflag,						"Food and Gun Locker",								dummyobj,				dummyobj,					_cf,								_cf,								true],
	[pub1,								"Pub",																dummyobj,				dummyobj,					_pub,								_pub,								true],
	[pub2,								"Pub",																dummyobj,				dummyobj,					_pub,								_pub,								true],
	[pub3,								"Pub",																dummyobj,				dummyobj,					_pub,								_pub,								true],
	[pub4,								"Pub",																dummyobj,				dummyobj,					_pub,								_pub,								true],
	[pub5,								"Saloon",															dummyobj,				dummyobj,					_pub,								_pub,								true],
	[martpub,							"Alcohol",														dummyobj,				dummyobj,					_pub,								_pub,								true],
	[assassinshop,				"Assassin Shop",											assassinshop,		dummyobj,					_ass,								_ass,								true],
	[mayorguns,						"Government Equip Shop",							mayorguns,			mayorcarspawn,		_mgs,								_mgs,								true],
	[equipbox,						"Equipment Shop",											equipbox,				dummyobj,					_es,								_es,								true],
	[equipbox2,						"Equipment Shop",											equipbox2,			dummyobj,					_es,								_es,								true],
	[tuning1,							"Car Upgrades",												dummyobj,				dummyobj,					_cu,								_cu,								true],
	[rMart,								"Car Items",													dummyobj,				dummyobj,					_rm,								_rm,								true],
	[carshop1,						"Used Cars",													dummyobj,				carspawn1,				_cs1,								_cs1,								true],
	[carshop4,						"Used Cars",													dummyobj,				carspawn4,				_cs1,								_cs1,								true],
	[carshop2,						"Farm Equipment",											dummyobj,				carspawn2,				_cs2,								_cs2,								false],
	[scarshop,						"Muscle Car Shop",										dummyobj,				scarspawn1,				_sc1,								_sc1,								true],
	[scarshop2,						"Charger and Mazda",									dummyobj,				scarspawn2,				_sc2,								_sc2,								true],
	[scarshop3,						"Low End Sports",											dummyobj,				scarspawn3,				_sc3,								_sc3,								true],
	[scarshop4,						"Mid Level Sports",										dummyobj,				scarspawn4,				_sc4,								_sc4,								true],
	[scarshop5,						"High End Sports",										dummyobj,				scarspawn5,				_sc5,								_sc5,								true],
	[scarshop6,						"Nissan Car Shop",										dummyobj,				scarspawn6,				_sc6,								_sc6,								true],
	[scarshop7,						"350z Car Shop",											dummyobj,				scarspawn7,				_sc7,								_sc7,								true],
	[scarshop8,						"Ford Car Shop",											dummyobj,				scarspawn8,				_sc8,								_sc8,								true],
	[scarshop9,						"BMW Car Shop",												dummyobj,				scarspawn9,				_sc9,								_sc9,								true],
	[tahoeshop1,					"Tahoe Shop",													dummyobj,				tahoespawn1,			_tahoe,							_tahoe,							true],
	[pickupshop1,					"Pickup Shop",												dummyobj,				pickupspawn1,			_ps,								_ps,								true],
	[taxishop,						"Taxi Shop",													dummyobj,				taxispawn1,				_tx,								_tx,								true],
	[bicycleshop,					"Bicycle Shop",												dummyobj,				bicyclespawn,			_bsj,								_bsj,								true],
	[bikeshop,						"Mikes Bike Shop",										dummyobj,				bikespawn,				_mbs,								_mbs,								true],
	[bikeshop1,						"Quad Bike Shop",											dummyobj,				bikespawn1,				_qbs,								_qbs,								true],
	[bikeshop2,						"Sports Bike Shop",										dummyobj,				bikespawn1,				_qbss,							_qbss,							true],
	[truckshop,						"Truck and Bus Shop",									dummyobj,				truckspawn,				_ts,								_ts,								true],
	[struckshop,					"Sport Truck Shop",										dummyobj,				struckspawn,			_sts,								_sts,								true],
	[airshop,							"Airplane Shop",											dummyobj,				asairspawn,				_as,								_as,								true],
	[airshop2,						"Chopper and Jet Shop",								dummyobj,				asairspawn,				_assa,							_assa,							true],
	[airshop3,						"Commercial Air Shop",								dummyobj,				asairspawn,				_asc,								_asc,								true],
	[AFP,									"Dem Airoplanes Store",								dummyobj,				AFPspawn,					_as,								_as,								true],
	[AFH,									"Dem Helamacopters Store",						dummyobj,				AFHspawn,					_assa,							_assa,							true],
	[scubashop, 					"Boat Shop",													dummyobj,				bs1spawn,					_bs,								_bs,								true],
	[boatshop2, 					"Boat Shop",													dummyobj,				boatspawn2,				_bs,								_bs,								true],
	[insure,							"Insurance",													insure,					dummyobj,					_ins, 							_emptyshop,					false],
	[tdoc,								"FireFighter 1",											dummyobj,				tdocspawn,				_td4,								_td4,								true],
	[tdoc6sub,						"FireFighter 1",											dummyobj,				tdocspawnsub,			_td4,								_td4,								true],
	[tdoc2,								"Untrained Equipment",								dummyobj,				tdocspawn,				_td,								_td,								true],
	[tdoc2sub,						"Untrained Equipment",								dummyobj,				tdocspawnsub,			_td,								_td,								true],
	[tdoc3,								"EMT 1 Equipment",										dummyobj,				tdocspawn,				_td2,								_td2,								true],
	[tdoc3sub,						"EMT 1 Equipment",										dummyobj,				tdocspawnsub,			_td2,								_td2,								true],
	[tdoc4,								"FireFighter 2",											dummyobj,				tdocspawn,				_td5,								_td5,								true],
	[tdoc4sub,						"FireFighter 2",											dummyobj,				tdocspawnsub,			_td5,								_td5,								true],
	[tdoc5,								"Air Rescue Equipment",								tdoc5,					jailpad2_1,				_td6,								_td6,								true],
	[tdoc5sub,						"Air Rescue Equipment",								tdoc5sub,				tdocspawnsubair,	_td6,								_td6,								true],
	[tdoc6,								"Command Equipment",									dummyobj,				tdocspawn,				_td7,								_td7,								true],
	[tdocsub,							"Command Equipment",									dummyobj,				tdocspawnsub,			_td7,								_td7,								true],
	[tdoc7,								"EMT 2 Equipment",										dummyobj,				tdocspawn,				_td3,								_td3,								true],
	[tdoc7sub,						"EMT 2 Equipment",										dummyobj,				tdocspawnsub,			_td3,								_td3,								true],
	[tdoc8,								"Fire Marshal Equipment",							dummyobj,				tdocspawn,				_td8,								_td8,								true],
	[resourcesell,				"Sell Resources",											dummyobj,				dummyobj,					_rs,								_rs,								true],
	[OL_Shop_Wigsworth,		"Wigworths",													dummyobj,				dummyobj,					_wigs,							_wigs,							true],
	[OilSell1,						"Oil Dealer", 												dummyobj,				dummyobj, 				_emptyshop,					_os,								true],
	[whalesell,						"Sell Whale",													dummyobj,				dummyobj,					_emptyshop,					_ws,								true],
	[terrorbox,						"Terror Stuff",												terrorbox,			vipterroraswpawn,	_terrorshop,				_terrorshop,				true],
	[shadyd,							"Barely Legal",												shadyd,					dummyobj,	 				_shady,							_shady,							true],
	[gangarea1,						"Gang Shop",													gangbox1,				dummyobj,					_gangshop_buy,			_gangshop_buy,			true],
	[gangarea2,						"Gang Shop",													gangbox2,				dummyobj,					_gangshop_buy,			_gangshop_buy,			true],
	[gangarea3,						"Gang Shop",													gangbox3,				dummyobj,					_gangshop_buy,			_gangshop_buy,			true],
	[gangarea4,						"Gang Shop",													gangbox4,				dummyobj,					_gangshop_buy,			_gangshop_buy,			true],
	[cdrugsell,						"Sell Cocaine",												dummyobj,				dummyobj,					_dsc,								_dsc,								true],
	[mdrugsell,						"Sell Marijuana",											dummyobj,				dummyobj,					_dsm,								_dsm,								true],
	[ldrugsell,						"Sell LSD",														dummyobj,				dummyobj,					_emptyshop,					_dsl,								true],
	[hdrugsell,						"Sell Heroin",												dummyobj,				dummyobj,					_dsh,								_dsh,								true],
	[methsell,						"Sell Meth",													dummyobj,				dummyobj,					_msc,								_msc,								true],
	[pharmacy,						"Pharmacy",														dummyobj,				pharmspawn,				_psc,								_emptyshop,					false],
	[copbasic1,						"Basic Police Gear",									copbasic1,			ccarspawn, 				_copbasic,					_copbasic,					true],
	[copbasic2,						"Basic Police Gear",									copbasic2,			ccarspawn,				_copbasic,					_copbasic,					true],
	[copbasic4,						"Basic Police Gear",									copbasic4,			ccarspawn, 				_copbasic,					_copbasic,					true],
	[copbasic6,						"Basic Police Gear",									copbasic6,			ccarspawn1, 			_copbasic,					_copbasic,					true],
	[copswate,						"Basic Police Gear",									copswate,				dummyobj, 				_copbasic,					_copbasic,					true],
	[copuntrained,				"Untrained Patrol Officer Equipment",	copuntrained,		ccarspawn,				_copuntrained,			_copuntrained,			true],
	[coppo1,							"Rookie Patrol Officer Equipment",		coppo1,					ccarspawn,				_coppo1,						_coppo1,						true],
	[coppo2,							"Patrol Officer Equipment",						coppo2,					ccarspawn,				_coppo2,						_coppo2,						true],
	[coppo3,							"Senior Patrol Officer Equipment",		coppo3,					ccarspawn,				_coppo3,						_coppo3,						true],
	[copcpl,							"Corporal Equipment",									copcpl,					ccarspawn2,				_copcpl,						_copcpl,						true],
	[copsgt,							"Sergeant Equipment",									copsgt,					ccarspawn2,				_copsgt,						_copsgt,						true],
	[copdeputy,						"Sheriff Deputy Equipment",						copdeputy,			ccarspawn1,				_copdeputy,					_copdeputy,					true],
	[copsgtdeputy,				"Sheriff Sgt Deputy Equipment",				copsgtdeputy,		ccarspawn1,				_copsgtdeputy,			_copsgtdeputy,			true],
	[copsheriffdnr,				"Sheriff D.N.R",											copsheriffdnr,	ccarspawn1,				_copsheriffdnr,			_copsheriffdnr,			true],
	[copsheriffmks,				"Sheriff Marksman",										copsheriffmks,	dummyobj,					_copsheriffmks,			_copsheriffmks,			true],
	[copsheriff,					"Sheriff Equipment",									copsheriff,			ccarspawn1,				_copsheriff,				_copsgt,						true],
	[coplt,								"Lieutenant Equipment",								coplt,					ccarspawnlt,			_coplt,							_coplt,							true],
	[copcpt,							"Captain Equipment",									copcpt,					ccarspawncpt,			_copcpt,						_copcpt,						true],
	[copmedalbox,					"Medal Recipients Equipment",					copmedalbox,		ccarspawnchief,		_copmedal,					_copmedal,					true],
	[copchief,						"Chief of Police Equipment",					copchief,				ccarspawnchief,		_copchief,					_copchief,					true],
	[copk9,								"K-9 Officer",												copk9,					ck9spawn,					_copk9,							_copk9,							true],
	[copk9p,							"K-9 Probation",											copk9p,					ck9spawn,					_copk9p,						_copk9p,						true],
	[copk9c,							"K-9 Command",												copk9c,					ck9spawn,					_copk9c,						_copk9c,						true],
	[copk92,							"Sheriff K-9 Equipment",							copk92,					ccarspawn1,				_copk9sheriff,			_copk9sheriff,			true],
	[copav1,							"Aviation",														copav1, 				cairspawn,				_copav1,						_copav1,						true],
	[copav2,							"Operation Pilot",										copav2, 				cairspawn,				_copav2,						_copav2,						true],
	[copav3,							"Air Patrol Operations",							dummyobj, 			copavapo,					_copav3,						_copav3,						true],
	[copair2,							"Sheriff Aviation",										copairweapon2, 	airsheriff,				_copavsh,						_copavsh,						true],
	[copswat1,						"S.W.A.T. Probation",									copswat1,				dummyobj,					_copswat1,					_copswat1,					true],
	[copswat2,						"S.W.A.T. Operator",									copswat2,				dummyobj,					_copswat2,					_copswat2,					true],
	[copswat3,						"S.W.A.T. Specialist",								copswat3,				dummyobj,					_copswat3,					_copswat3,					true],
	[copswat4,						"S.W.A.T. Marksman",									copswat4,				dummyobj,					_copswat4,					_copswat4,					true],
	[copswat5,						"S.W.A.T. Command",										copswat5,				dummyobj,					_copswat5,					_copswat5,					true],
	[swatcg,							"S.W.A.T. Water Craft",								dummyobj,				cgboatspawn,			_copswat6,					_copswat6,					true],
	[copswatvehicle,			"S.W.A.T. Vehicles",									dummyobj,				ccarspawnswat,		_copswatvehicle,		_copswatvehicle,		true],
	[cidbox,							"CID Equipment",											cidbox,					cidcarspawn,			_cid,								_cid,								true],
	[copcoastguard,				"Sheriff Marine Water Craft",					dummyobj,				cgboatspawn,			_copcoastguard,			_copcoastguard,			true],
	[copcoastguardair,		"Sheriff Marine Aviation",						dummyobj,				jailpadcg,				_copcoastguardair,	_copcoastguardair,	true],
	[ftobox,							"F.T.O Equipment",										ftobox,					ftocarspawn,			_copfto,						_copfto,						true],
	[copVIPBox,						"Cop Donator Equipment",							copVIPBox,			ccarspawn,				_copvip,						_copvip,						true],
	[copVIPBox2,					"Cop Donator Equipment",							copVIPBox2,			ccarspawn1,				_copvip,						_copvip,						true],
	[copVIPBox3,					"Cop Donator Equipment",							copVIPBox3,			ccarspawn2,				_copvip,						_copvip,						true],
	[copswatd,						"Cop Donator Equipment",							copswatd,				ccarspawn2,				_copvip,						_copvip,						true],
	[copcidd,							"Cop Donator Equipment",							copcidd,				cidcarspawn,			_copvip,						_copvip,						true],
	[dshop1,							"Donator Shop (Tier 1)",							maindonateshop,	dummyobj,					_Donate,						_Donate,						true],
	[dshop2,							"Donator Shop (Tier 2)",							donateshop2,		donatespawn2,			_Donate2,						_Donate2,						true],
	[dshop3,							"Donator Shop (Tier 3)",							donateshop3,		donatespawn3,			_Donate3,						_Donate3,						true],
	[dshop4,							"Donator Shop (Tier 4)",							donateshop4,		donatespawn4,			_Donate4,						_Donate4,						true],
	[dshop5,							"Donator Shop (Tier 5)",							donateshop5,		dummyobj,					_Donate5,						_Donate5,						true],
	[dshop6,							"Donator Shop (Tier 6)",							donateshop6,		dummyobj,					_Donate6,						_Donate6,						true],
	[terrorvip,						"Terror VIP Shop",										terrorvip,			vipterroraswpawn,	_VIPterror,					_VIPterror,					true],
	[Diamond_1,						"Pawn Shop",													dummyobj,				dummyobj,					_js,								_js,								true],
	[vipterrorair,				"VIP Terror Air Shop",								vipterrorair,		vipterroraswpawn,	_vipterrorairlist,	_vipterrorairlist,	true],
	[hospsell,						"Sell Organs",												dummyobj,				dummyobj,					_hsc,								_hsc,								true],
	[pmcbox,							"PMC Operator",												pmcbox,					pmcspawn,					_PMC,								_PMC,								true],
	[pmcbox1,							"PMC Command",												pmcbox1,				pmcspawn,					_CommandPMC,				_CommandPMC,				true],
	[pmcbox2,							"PMC Air",														dummyobj,				pmchelipad,				_PMCAIR,						_PMCAIR,						true],
	[towfoodshop,					"Flyer's Vending Machine",						dummyobj,				dummyobj,					_Tow,								_Tow,								true],
	[tow_box,							"Parts Box",													dummyobj,				dummyobj,					_Tow1,							_Tow1,							true],
	[towcarshop,					"Junior Mechanic",										dummyobj,				tow_spawn,				_Tow2,							_Tow2,							true],
	[towcarshop_1,				"Senior Supervisor",									dummyobj,				tow_spawn,				_Tow3,							_Tow3,							true],
	[towcarshop_2,				"Mechanic Supervisor",								dummyobj,				tow_spawn,				_Tow4,							_Tow4,							true]
];

OL_Shops = INV_ItemShops; // temp
