/************************ Common ************************/

#include "dialog\RscDefines.hpp"
#include "dialog\RscTitles.hpp"
#include "dialog\common.hpp"

/************************ Other Bullshit ************************/

#include "dialog\2085272.hpp"
#include "dialog\4461230.hpp"
#include "dialog\4782911.hpp"
#include "dialog\adminpanel.hpp"
#include "dialog\animdlg.hpp"
#include "dialog\bank.hpp"
#include "dialog\bankcodedlg.hpp"
#include "dialog\compsystem.hpp"
#include "dialog\defines.hpp"
#include "dialog\dialog.hpp"
#include "dialog\dialog_callcopsemts.hpp"
#include "dialog\dlg_attente_reanimation.h"
#include "dialog\gfx.hpp"
#include "dialog\interaction_menu.hpp"
#include "dialog\interaction_menucop.hpp"
#include "dialog\invdialogs.hpp"
#include "dialog\maindialogs.hpp"
#include "dialog\mdc.hpp"
#include "dialog\menuv2.hpp"
#include "dialog\msg.hpp"
#include "dialog\phone.hpp"
#include "dialog\spawn_dialog.hpp"
#include "dialog\swagswag.hpp"
#include "dialog\swagswagcop.hpp"
#include "dialog\swagswagesu.hpp"
#include "dialog\ui_checkpoint.hpp"
#include "dialog\ui_clothesmenu.hpp"
//#include "dialog\ui_gangmenu.hpp"
