//Made by 'i dont fucking know'
//Editied by CP3088
//@CP'sDevs: "IF YOU DONT FUCKING KEEP THIS FORMAT I WILL SLIT YOUR THROAT"

INV_Lizenzen =
[
  ["RLRPG_Clothing_license", [atmmall, OL_Shop_ClothingStore_1, OL_Shop_ClothingStore_2], "Our Life RPG Clothing License",                  150000,   civilian],
  ["hunting_license",        [atmswag],                                                   "Hunting license",                                20000,    civilian],
  ["hunting_license",        [scubashop, scubashop, boatshop2],                           "Fishing license",                                20000,    civilian],
  ["pistol",                 [atmswag, OL_Shop_Undercover],                               "Pistol license",                                 50000,    civilian],
  ["sub",                    [atmswag],                                                   "Submachine Gun license",                         100000,   civilian],
  ["rifle",                  [atmswag, OL_Shop_Undercover],                               "Rifle license",                                  150000,   civilian],
  ["mayorlic",               [dmv],                                                       "Governors license",                              1000,     civilian],
  ["boat",                   [dmv, atm10],                                                "Boat License",                                   1500,     civilian],
  ["fboat",                  [dmv],                                                       "Ferry Captain License",                          2500,     civilian],
  ["air",                    [airshop, pmcbank],                                          "Pilots License",                                 35000,    civilian],
  ["comair",                 [airshop3],                                                  "Commerical Air License",                         100000,   civilian],
  ["esul",                   [atm5, atmsubfire],                                          "Untrained License",                              100,      resistance],
  ["esul2",                  [atm5, atmsubfire],                                          "EMT 1 License",                                  100,      "EMT1_id"],
  ["esul3",                  [atm5, atmsubfire],                                          "EMT 2 License",                                  100,      "EMT2_id"],
  ["esul7",                  [atm5, atmsubfire],                                          "FireFighter 1 License",                          100,      "FD_id"],
  ["esul4",                  [atm5, atmsubfire],                                          "FireFighter 2 License",                          100,      "FD_id"],
  ["esul5",                  [atm5, atmsubfire],                                          "EMT Air License",                                100,      "AirESU_id"],
  ["esul6",                  [atm5, atmsubfire],                                          "ESU Command  License",                           100,      "EMTSupervisor_id"],
  ["bus_license",            [truckshop],                                                 "Bus License",                                    1000,     civilian],
  ["truck",                  [truckshop],                                                 "Truck License",                                  5000,     civilian],
  ["taxi",                   [taxishop],                                                  "Taxi License",                                   5000,     civilian],
  ["car",                    [dmv, OL_Shop_Undercover, atm10],                            "Drivers License",                                2500,     civilian],
  ["oil",                    [Oil_1],                                                     "Oil processor's license",                        10000,    civilian],
  ["Baker",                  [Bakery],                                                    "Baker's license",                                10000,    civilian],
  ["cocaine ga1",            [OL_Shop_Gangarea1],                                         "West Cocaine Drug processor's license",          50000,    civilian],
  ["lsd ga1",                [OL_Shop_Gangarea1],                                         "West LSD Drug processor's license",              50000,    civilian],
  ["heroin ga2",             [OL_Shop_Gangarea2],                                         "Havana Heroin Drug processor's license",         50000,    civilian],
  ["lsd ga2",                [OL_Shop_Gangarea2],                                         "Havana LSD Drug processor's license",            50000,    civilian],
  ["heroin ga3",             [OL_Shop_Gangarea3],                                         "East Heroin Drug processor's license",           50000,    civilian],
  ["marijuana ga3",          [OL_Shop_Gangarea3],                                         "East Marijuana Drug processor's license",        50000,    civilian],
  ["heroin ga4",             [OL_Shop_Gangarea4],                                         "Safe House Heroin Drug processor's license",     50000,    civilian],
  ["marijuana ga4",          [OL_Shop_Gangarea4],                                         "Safe House Marijuana Drug processor's license",  50000,    civilian],
  ["assassinlic",            [assassinshop],                                              "Illegal Assassin Weapons Fee",                   500000,   civilian],
  ["terror",                 [terrorbox],                                                 "Illegal Terrorist License",                      999999,   civilian],
  ["PatrolBasic_license",    [copbank, copcmdbank, OL_Shop_Undercover, copsheriffbank],   "Basic Patrol License",                           1000,     west],
  ["K9_license",             [copdispatchbank, copsheriffbank],                           "K-9 Officer License",                            10000,    "K9_id"],
  ["PDAviation_license",     [copairbank],                                                "PD Aviation License",                            10000,    "PDAviation_id"],
  ["SWAT_license",           [copswatbank],                                               "S.W.A.T. License",                               10000,    "SWAT_id"],
  ["CoastGuard_license",     [copcoastguardbank],                                         "Sheriff Marine License",                         10000,    "CoastGuard_id"],
  ["Chief_license",          [copcmdbank],                                                "Chief of Police License",                        10000,    "Chief_id"],
  ["Captain_license",        [copcmdbank],                                                "Captain License",                                10000,    "Cpt_id"],
  ["Lieutenant_license",     [copcmdbank],                                                "Lieutenant License",                             10000,    "Lt_id"],
  ["Sergeant_license",       [copsgtbank],                                                "Sergeant License",                               10000,    "Sgt_id"],
  ["Corporal_license",       [copsgtbank],                                                "Corporal License",                               10000,    "Cpl_id"],
  ["FTO_license",            [ftobox],                                                    "FTO License",                                    10000,    "FTO_id"],
  ["Deputy_license",         [copsheriffbank],                                            "Deputy License",                                 10000,    "JrDeputy_id"],
  ["SgtDeputy_license",      [copsheriffbank],                                            "Sergeant Deputy License",                        10000,    "SgtDeputy_id"],
  ["Sheriff_license",        [copsheriffbank],                                            "Sheriff License",                                10000,    "Sheriff_id"],
  ["CID_license",            [cidbank],                                                   "CID License",                                    10000,    "Undercover_id"],
  ["Undercover_license",     [OL_Shop_Undercover],                                        "Undercover License",                             10000,    "Undercover_id"],
  ["towl",                   [truckshop,towatm],                                          "Towing License",                                 30000,    civilian],
  ["PMC_license",            [pmcbank],                                                   "PMC License",                                    100000,   "PMC_id"],
  ["CommandPMC_license",     [pmcbank],                                                   "PMC Command License",                            50000,    "CommandPMC_id"],
  ["Field_Medic",            [pharmacy],                                                  "Field Medic Training",                           75000,    civilian]
];

INV_LizenzOwner = [];
