//Made by 'i dont fucking know'
//Editied by CP3088
//@CP'sDevs: "IF YOU DONT FUCKING KEEP THIS FORMAT I WILL SLIT YOUR THROAT"

INV_Lizenzen =
[
  ["RLRPG_Clothing_license", [atmmall, OL_Shop_ClothingStore_1, OL_Shop_ClothingStore_2],      "Our Life RPG Clothing License",150000],
  ["hunting_license",        [atmswag],                                                "Hunting license",20000],
  ["hunting_license",        [scubashop, scubashop, boatshop2],                        "Fishing license",20000],
  ["pistol",                 [atmswag, OL_Shop_Undercover],                                       "Pistol license",50000],
  ["sub",                    [atmswag],                                                "Submachine Gun license",100000],
  ["rifle",                  [atmswag, OL_Shop_Undercover],                                       "Rifle license",150000],
  ["mayorlic",               [dmv],                                                    "Governors license",1000],
  ["boat",                   [dmv, atm10, atm1],                                       "Boat License",1500],
  ["fboat",                  [dmv, atm1],                                              "Ferry Captain License",2500],
  ["air",                    [atm1, airshop, pmcbank],                                 "Pilots License",35000],
  ["comair",                 [atm1, airshop3],                                         "Commerical Air License",100000],
  ["viptl",                  [atm1, terrorvip],                                        "Terror VIP License",800000],
  ["esul",                   [atm5, atmsubfire],                                       "Untrained License",100],
  ["esul2",                  [atm5, atmsubfire],                                       "EMT 1 License",100],
  ["esul3",                  [atm5, atmsubfire],                                       "EMT 2 License",100],
  ["esul7",                  [atm5, atmsubfire],                                       "FireFighter 1 License",100],
  ["esul4",                  [atm5, atmsubfire],                                       "FireFighter 2 License",100],
  ["esul5",                  [atm5, atmsubfire],                                       "EMT Air License",100],
  ["esul6",                  [atm5, atmsubfire],                                       "ESU Command  License",100],
  ["bus_license",            [truckshop],                                              "Bus License",1000],
  ["truck",                  [truckshop],                                              "Truck License",5000],
  ["taxi",                   [taxishop],                                               "Taxi License",5000],
  ["car",                    [dmv, OL_Shop_Undercover, atm1, atm10],                              "Drivers License",2500],
  ["oil",                    [Oil_1],                                                  "Oil processor's license",10000],
  ["Baker",                  [Bakery],                                                 "Baker's license",10000],
  ["cocaine ga1",            [OL_Shop_Gangarea1],                                              "West Cocaine Drug processor's license",50000],
  ["lsd ga1",                [OL_Shop_Gangarea1],                                              "West LSD Drug processor's license",50000],
  ["heroin ga2",             [OL_Shop_Gangarea2],                                              "Havana Heroin Drug processor's license",50000],
  ["lsd ga2",                [OL_Shop_Gangarea2],                                              "Havana LSD Drug processor's license",50000],
  ["heroin ga3",             [OL_Shop_Gangarea3],                                              "East Heroin Drug processor's license",50000],
  ["marijuana ga3",          [OL_Shop_Gangarea3],                                              "East Marijuana Drug processor's license",50000],
  ["heroin ga4",             [OL_Shop_Gangarea4],                                              "Safe House Heroin Drug processor's license",50000],
  ["marijuana ga4",          [OL_Shop_Gangarea4],                                              "Safe House Marijuana Drug processor's license",50000],
  ["assassinlic",            [assassinshop],                                           "Illegal Assassin Weapons Fee",500000],
  ["terror",                 [terrorbox],                                              "Illegal Terrorist License",999999],
  ["Donator_license",        [maindonateshop],                                         "Donator license Tier 1",50000],
  ["Donator_license2",       [donateshop2],                                            "Donator license Tier 2",50000],
  ["Donator_license3",       [donateshop3],                                            "Donator License Tier 3",50000],
  ["Donator_license4",       [donateshop4],                                            "Donator License Tier 4",50000],
  ["Donator_license5",       [donateshop5],                                            "Donator License Tier 5",50000],
  ["Donator_license6",       [donateshop6],                                            "Donator License Tier 6",50000],
  ["tierx",                  [weaponx, itemx, carx, boatx, helix],                     "Tier X General License",80000],
  ["PatrolBasic_license",    [copbank, copcmdbank, OL_Shop_Undercover, copsheriffbank],           "Basic Patrol License",1000],
  ["K9_license",             [copdispatchbank, copsheriffbank],                        "K-9 Officer License",10000],
  ["PDAviation_license",     [copairbank],                                             "PD Aviation License",10000],
  ["SWAT_license",           [copswatbank],                                            "S.W.A.T. License",10000],
  ["CoastGuard_license",     [copcoastguardbank],                                      "Sheriff Marine License",10000],
  ["Chief_license",          [copcmdbank],                                             "Chief of Police License",10000],
  ["Captain_license",        [copcmdbank],                                             "Captain License",10000],
  ["Lieutenant_license",     [copcmdbank],                                             "Lieutenant License",10000],
  ["Sergeant_license",       [copsgtbank],                                             "Sergeant License",10000],
  ["Corporal_license",       [copsgtbank],                                             "Corporal License",10000],
  ["FTO_license",            [ftobox],                                                 "FTO License",10000],
  ["cor_license",            [atmjail],                                                "Corrections License",10000],
  ["vipcl",                  [copbank, OL_Shop_Undercover, copsheriffbank, copcmdbank],  "Cop Donator License",100000],
  ["Deputy_license",         [copsheriffbank],                                         "Deputy License",10000],
  ["SgtDeputy_license",      [copsheriffbank],                                         "Sergeant Deputy License",10000],
  ["Sheriff_license",        [copsheriffbank],                                         "Sheriff License",10000],
  ["CID_license",            [cidbank],                                                "CID License",10000],
  ["Undercover_license",     [OL_Shop_Undercover],                                                "Undercover License",10000],
  ["towl",                   [truckshop,towatm],                                       "Towing License",30000],
  ["PMC_license",            [pmcbank],                                                "PMC License",100000],
  ["CommandPMC_license",     [pmcbank],                                                "PMC Command License",50000]
];

INV_LizenzOwner = [];
